import java.util.Scanner;
import java.util.Random;

public class NumberGuessing {
    public static void main(String args[]){
        // //Number guessing using Random class and do while loop
        // Random random = new Random();
        // Scanner scanner = new Scanner(System.in);

        // int aiGenerated = random.nextInt(0,11);
        // int guess;

        // System.out.print ("Enter a number between 0 to 10: ");
        // guess = scanner.nextInt();
        // System.out.printf("The Random number generated by Computer is: %d\n",aiGenerated);
        // String result = (guess == aiGenerated) ? "Hurray!! Its a Match" : "Its not a match. Try Again";
        // System.out.println(result);
        // scanner.close();
         //here the code is basic it doesnt check any conditions of emplty 
         //or number enetered i graeter than 10 or less than 0


        Random random = new Random();
        Scanner scanner = new Scanner(System.in);

        int aiGenerated = random.nextInt(0,11);
        int guess;
        int attempts = 0;
        do{
            System.out.print ("Enter a number between 0 to 10: ");
            guess = scanner.nextInt();  
            attempts++;
            while(guess != aiGenerated){
                if(guess < aiGenerated){
                    System.out.printf("Higher than your guess, Try Again !!!!\n ");
                }
                else{
                    System.out.printf("Lower than your guess, Try Again !!!!\n ");
                }
                break;
            }
            
        } while(guess >= 0 && guess <= 10 && guess != aiGenerated );
    
        System.out.printf("\nTherefore Random number generated by Computer is: %d\n",aiGenerated);
        String result = (guess == aiGenerated) ? "<-----Hurray!! Its a Match------->" : "Its not a match. Try Again";
        System.out.println(result);
        System.out.println("No. of your attempts to guess a number: "+attempts);
        scanner.close();
    }
    
}
